[Win11Box1]
Meter=Shape
MeterStyle=Win11BoxStyle
[Win11Box1Icon]
Meter=Image
MeterStyle=Win11IconStyle
[Win11Box1Text]
Meter=String
MeterStyle=RegularText | Win11TextStyle
[Win11Box2]
Meter=Shape
MeterStyle=Win11BoxStyle
[Win11Box2Icon]
Meter=Image
MeterStyle=Win11IconStyle
[Win11Box2Text]
Meter=String
MeterStyle=RegularText | Win11TextStyle
[Win11Box3]
Meter=Shape
MeterStyle=Win11BoxStyle
[Win11Box3Icon]
Meter=Image
MeterStyle=Win11IconStyle
[Win11Box3Text]
Meter=String
MeterStyle=RegularText | Win11TextStyle
[Win11Box4]
Meter=Shape
MeterStyle=Win11BoxStyle
[Win11Box4Icon]
Meter=Image
MeterStyle=Win11IconStyle
[Win11Box4Text]
Meter=String
MeterStyle=RegularText | Win11TextStyle
[Win11Box5]
Meter=Shape
MeterStyle=Win11BoxStyle
[Win11Box5Icon]
Meter=Image
MeterStyle=Win11IconStyle
[Win11Box5Text]
Meter=String
MeterStyle=RegularText | Win11TextStyle
[Win11Box6]
Meter=Shape
MeterStyle=Win11BoxStyle
[Win11Box6Icon]
Meter=Image
MeterStyle=Win11IconStyle
[Win11Box6Text]
Meter=String
MeterStyle=RegularText | Win11TextStyle
[Win11Box7]
Meter=Shape
MeterStyle=Win11BoxStyle | Win11BoxNewRowStyle
[Win11Box7Icon]
Meter=Image
MeterStyle=Win11IconStyle
[Win11Box7Text]
Meter=String
MeterStyle=RegularText | Win11TextStyle
[Win11Box8]
Meter=Shape
MeterStyle=Win11BoxStyle
[Win11Box8Icon]
Meter=Image
MeterStyle=Win11IconStyle
[Win11Box8Text]
Meter=String
MeterStyle=RegularText | Win11TextStyle
[Win11Box9]
Meter=Shape
MeterStyle=Win11BoxStyle
[Win11Box9Icon]
Meter=Image
MeterStyle=Win11IconStyle
[Win11Box9Text]
Meter=String
MeterStyle=RegularText | Win11TextStyle
[Win11Box10]
Meter=Shape
MeterStyle=Win11BoxStyle
[Win11Box10Icon]
Meter=Image
MeterStyle=Win11IconStyle
[Win11Box10Text]
Meter=String
MeterStyle=RegularText | Win11TextStyle
[Win11Box11]
Meter=Shape
MeterStyle=Win11BoxStyle
[Win11Box11Icon]
Meter=Image
MeterStyle=Win11IconStyle
[Win11Box11Text]
Meter=String
MeterStyle=RegularText | Win11TextStyle
[Win11Box12]
Meter=Shape
MeterStyle=Win11BoxStyle
[Win11Box12Icon]
Meter=Image
MeterStyle=Win11IconStyle
[Win11Box12Text]
Meter=String
MeterStyle=RegularText | Win11TextStyle
