[Win11Box1]
Meter=Shape
MeterStyle=Win11BoxStyle
LeftMouseUpAction=["#SKINSPATH#..\CoreData\ValliStart\DefaultShortcuts\YouTube.url"]
[Win11Box1Icon]
Meter=Image
MeterStyle=Win11IconStyle
ImageName="YouTube_url.png"
[Win11Box1Text]
Meter=String
MeterStyle=RegularText | Win11TextStyle
Text=YouTube
[Win11Box2]
Meter=Shape
MeterStyle=Win11BoxStyle
LeftMouseUpAction=["#SKINSPATH#..\CoreData\CoreData\ValliStart\DefaultShortcuts\JaxCore.lnk"]
[Win11Box2Icon]
Meter=Image
MeterStyle=Win11IconStyle
ImageName="JaxCore_lnk.png"
[Win11Box2Text]
Meter=String
MeterStyle=RegularText | Win11TextStyle
Text=JaxCore
[Win11Box3]
Meter=Shape
MeterStyle=Win11BoxStyle
LeftMouseUpAction=["#SKINSPATH#..\CoreData\CoreData\ValliStart\DefaultShortcuts\DIscord.lnk"]
[Win11Box3Icon]
Meter=Image
MeterStyle=Win11IconStyle
ImageName="DIscord_lnk.png"
[Win11Box3Text]
Meter=String
MeterStyle=RegularText | Win11TextStyle
Text=DIscord
[Win11Box4]
Meter=Shape
MeterStyle=Win11BoxStyle
LeftMouseUpAction=["#SKINSPATH#..\CoreData\CoreData\ValliStart\DefaultShortcuts\Spotify.lnk"]
[Win11Box4Icon]
Meter=Image
MeterStyle=Win11IconStyle
ImageName="Spotify_lnk.png"
[Win11Box4Text]
Meter=String
MeterStyle=RegularText | Win11TextStyle
Text=Spotify
[Win11Box5]
Meter=Shape
MeterStyle=Win11BoxStyle
LeftMouseUpAction=["#SKINSPATH#..\CoreData\CoreData\ValliStart\DefaultShortcuts\Reddit.lnk"]
[Win11Box5Icon]
Meter=Image
MeterStyle=Win11IconStyle
ImageName="Reddit_lnk.png"
[Win11Box5Text]
Meter=String
MeterStyle=RegularText | Win11TextStyle
Text=Reddit
[Win11Box6]
Meter=Shape
MeterStyle=Win11BoxStyle
LeftMouseUpAction=["#SKINSPATH#..\CoreData\CoreData\ValliStart\DefaultShortcuts\Google Translate.lnk"]
[Win11Box6Icon]
Meter=Image
MeterStyle=Win11IconStyle
ImageName="Google Translate_lnk.png"
[Win11Box6Text]
Meter=String
MeterStyle=RegularText | Win11TextStyle
Text=Google Translate
[Win11Box7]
Meter=Shape
MeterStyle=Win11BoxStyle | Win11BoxNewRowStyle
LeftMouseUpAction=["#SKINSPATH#..\CoreData\CoreData\ValliStart\DefaultShortcuts\DeviantArt.lnk"]
[Win11Box7Icon]
Meter=Image
MeterStyle=Win11IconStyle
ImageName="DeviantArt_lnk.png"
[Win11Box7Text]
Meter=String
MeterStyle=RegularText | Win11TextStyle
Text=DeviantArt
[Win11Box8]
Meter=Shape
MeterStyle=Win11BoxStyle
LeftMouseUpAction=["#SKINSPATH#..\CoreData\CoreData\ValliStart\DefaultShortcuts\Google Photos.lnk"]
[Win11Box8Icon]
Meter=Image
MeterStyle=Win11IconStyle
ImageName="Google Photos_lnk.png"
[Win11Box8Text]
Meter=String
MeterStyle=RegularText | Win11TextStyle
Text=Google Photos
[Win11Box9]
Meter=Shape
MeterStyle=Win11BoxStyle
LeftMouseUpAction=["#SKINSPATH#..\CoreData\CoreData\ValliStart\DefaultShortcuts\Gmail.lnk"]
[Win11Box9Icon]
Meter=Image
MeterStyle=Win11IconStyle
ImageName="Gmail_lnk.png"
[Win11Box9Text]
Meter=String
MeterStyle=RegularText | Win11TextStyle
Text=Gmail
[Win11Box10]
Meter=Shape
MeterStyle=Win11BoxStyle
LeftMouseUpAction=["#SKINSPATH#..\CoreData\CoreData\ValliStart\DefaultShortcuts\The Weather Channel.lnk"]
[Win11Box10Icon]
Meter=Image
MeterStyle=Win11IconStyle
ImageName="The Weather Channel_lnk.png"
[Win11Box10Text]
Meter=String
MeterStyle=RegularText | Win11TextStyle
Text=The Weather Channel
[Win11Box11]
Meter=Shape
MeterStyle=Win11BoxStyle
LeftMouseUpAction=["#SKINSPATH#..\CoreData\CoreData\ValliStart\DefaultShortcuts\Google Maps.lnk"]
[Win11Box11Icon]
Meter=Image
MeterStyle=Win11IconStyle
ImageName="Google Maps_lnk.png"
[Win11Box11Text]
Meter=String
MeterStyle=RegularText | Win11TextStyle
Text=Google Maps
[Win11Box12]
Meter=Shape
MeterStyle=Win11BoxStyle
LeftMouseUpAction=["#SKINSPATH#..\CoreData\CoreData\ValliStart\DefaultShortcuts\Wordle.lnk"]
[Win11Box12Icon]
Meter=Image
MeterStyle=Win11IconStyle
ImageName="Wordle_lnk.png"
[Win11Box12Text]
Meter=String
MeterStyle=RegularText | Win11TextStyle
Text=Wordle