[Top.String]
Text=Welcome modules

[GenericHeader.Shape]
Meter=Shape
X=(#SEc.P#)
Y=(40*[S])r
MeterStyle=Module.Shape:S
[GenericHeader.Image]
Meter=Image
MeterStyle=Module.Image:S
[GenericHeader.String]
Meter=String
MEterStyle=Sec.String:S | Module.STring:S
[GenericHeader.Description.String]
Meter=String
Text=The default header module for ValliStart.
MEterStyle=Sec.String:S | Module.Description.STring:S

[SearchBar.Shape]
Meter=Shape
MeterStyle=Module.Shape:S
[SearchBar.Image]
Meter=Image
MeterStyle=Module.Image:S
[SearchBar.String]
Meter=String
MEterStyle=Sec.String:S | Module.STring:S
[SearchBar.Description.String]
Meter=String
Text=A button which sends a hotkey, which the default key is to open the search menu.
MEterStyle=Sec.String:S | Module.Description.STring:S

[Weather.Shape]
Meter=Shape
MeterStyle=Module.Shape:S
[Weather.Image]
Meter=Image
MeterStyle=Module.Image:S
[Weather.String]
Meter=String
MEterStyle=Sec.String:S | Module.STring:S
[Weather.Description.String]
Meter=String
Text=Shows Today's and Tomorrow's weather and temperature
MEterStyle=Sec.String:S | Module.Description.STring:S