[Top.String]
Text=Shortcut modules



[Win11Row.Shape]
Meter=Shape
X=(#SEc.P#)
Y=(#Sec.P#*3+40*[S])
MeterStyle=Module.Shape:S
[Win11Row.Image]
Meter=Image
MeterStyle=Module.Image:S
[Win11Row.String]
Meter=String
MEterStyle=Sec.String:S | Module.STring:S
[Win11Row.Description.String]
Meter=String
Text=A gallery of shortcuts which is visually similar to the Windows 11 pinned shortcuts
MEterStyle=Sec.String:S | Module.Description.STring:S

[DoubleRow.Shape]
Meter=Shape
MeterStyle=Module.Shape:S
[DoubleRow.Image]
Meter=Image
MeterStyle=Module.Image:S
[DoubleRow.String]
Meter=String
MEterStyle=Sec.String:S | Module.STring:S
[DoubleRow.Description.String]
Meter=String
Text=2 Rows of 5 Boxes of shortcuts.
MEterStyle=Sec.String:S | Module.Description.STring:S

[SingleRow.Shape]
Meter=Shape
MeterStyle=Module.Shape:S
[SingleRow.Image]
Meter=Image
MeterStyle=Module.Image:S
[SingleRow.String]
Meter=String
MEterStyle=Sec.String:S | Module.STring:S
[SingleRow.Description.String]
Meter=String
Text=1 Row of 5 shortcuts
MEterStyle=Sec.String:S | Module.Description.STring:S