[Top.String]
Text=DLC - Vekl

[VeklBarHeader.Shape]
Meter=Shape
X=(#SEc.P#)
Y=(#Sec.P#)r
MeterStyle=Module.Shape:S
[VeklBarHeader.Image]
Meter=Image
MeterStyle=Module.Image:S
[VeklBarHeader.String]
Meter=String
MEterStyle=Sec.String:S | Module.STring:S
[VeklBarHeader.Description.String]
Meter=String
Text=
MEterStyle=Sec.String:S | Module.Description.STring:S

[VeklBigHeader.Shape]
Meter=Shape
MeterStyle=Module.Shape:S
[VeklBigHeader.Image]
Meter=Image
MeterStyle=Module.Image:S
[VeklBigHeader.String]
Meter=String
MEterStyle=Sec.String:S | Module.STring:S
[VeklBigHeader.Description.String]
Meter=String
Text=
MEterStyle=Sec.String:S | Module.Description.STring:S

[VeklVolume.Shape]
Meter=Shape
MeterStyle=Module.Shape:S
[VeklVolume.Image]
Meter=Image
MeterStyle=Module.Image:S
[VeklVolume.String]
Meter=String
MEterStyle=Sec.String:S | Module.STring:S
[VeklVolume.Description.String]
Meter=String
Text=
MEterStyle=Sec.String:S | Module.Description.STring:S

[VeklDWF.Shape]
Meter=Shape
X=(#SEc.P#)
Y=(#Sec.P#*3+20*[S])r
MeterStyle=Module.Shape:S
[VeklDWF.Image]
Meter=Image
MeterStyle=Module.Image:S
[VeklDWF.String]
Meter=String
MEterStyle=Sec.String:S | Module.STring:S
[VeklDWF.Description.String]
Meter=String
Text=
MEterStyle=Sec.String:S | Module.Description.STring:S

[VeklMusic.Shape]
Meter=Shape
MeterStyle=Module.Shape:S
[VeklMusic.Image]
Meter=Image
MeterStyle=Module.Image:S
[VeklMusic.String]
Meter=String
MEterStyle=Sec.String:S | Module.STring:S
[VeklMusic.Description.String]
Meter=String
Text=
MEterStyle=Sec.String:S | Module.Description.STring:S

[VeklQuote.Shape]
Meter=Shape
MeterStyle=Module.Shape:S
[VeklQuote.Image]
Meter=Image
MeterStyle=Module.Image:S
[VeklQuote.String]
Meter=String
MEterStyle=Sec.String:S | Module.STring:S
[VeklQuote.Description.String]
Meter=String
Text=
MEterStyle=Sec.String:S | Module.Description.STring:S

[VeklResource.Shape]
Meter=Shape
X=(#SEc.P#)
Y=(#Sec.P#*3+20*[S])r
MeterStyle=Module.Shape:S
[VeklResource.Image]
Meter=Image
MeterStyle=Module.Image:S
[VeklResource.String]
Meter=String
MEterStyle=Sec.String:S | Module.STring:S
[VeklResource.Description.String]
Meter=String
Text=
MEterStyle=Sec.String:S | Module.Description.STring:S