[Variables]
Accent=35, 159, 255
Font=Seoge UI
Scale=1
Corner=1
Edge=1
Alpha=250

Player=WNP
NPName=Spotify
FetchImage=1

Location=Center
ShowSec=0
Animated=1
Acrylic=None

Monitor=3

Color=36,36,36
Border=54,54,54
FontColor=255,255,255
DarkColor=190,190,190
BoxBorder=80,80,80
BoxColor=60,60,60

;;╔══════════════════════════════════════════════════════════════════════════════════════════════════════╗
;;║ METERSTYLES                                                                                          ║
;;╚══════════════════════════════════════════════════════════════════════════════════════════════════════╝


[BoldText]
FontFace=#Font#
FontWeight=800
AntiAlias=1
FontColor=#FontColor#
FontSize=(12*#Scale#)
SolidColor=0,0,0,1

[SemiBoldText]
FontFace=#Font#
FontWeight=500
AntiAlias=1
FontColor=#FontColor#
FontSize=(12*#Scale#)
SolidColor=0,0,0,1

[RegularText]
FontFace=#Font#
AntiAlias=1
FontColor=#FontColor#
FontSize=(12*#Scale#)
SolidColor=0,0,0,1
