[Variables]
ReplaceWin=1
2412=H
StartText=Start
IconName=Win

Font=Poppins Light
Scale=1
Corner=1
Stroke=1
Edge=15

Player=WNP
NPName=Spotify
FetchImage=1

Location=Center
ShowSec=0
Animated=1
Blur=None

Monitor=3

Accent=35,159,255
Alpha=255
Color=36,36,36
Border=54,54,54
FontColor=255,255,255
DarkColor=190,190,190
BoxBorder=80,80,80
BoxColor=60,60,60

;;╔══════════════════════════════════════════════════════════════════════════════════════════════════════╗
;;║ METERSTYLES                                                                                          ║
;;╚══════════════════════════════════════════════════════════════════════════════════════════════════════╝


[BoldText]
FontFace=#Font#
FontWeight=800
AntiAlias=1
FontColor=#FontColor#
FontSize=(11*#Scale#)
SolidColor=0,0,0,1

[SemiBoldText]
FontFace=#Font#
FontWeight=500
AntiAlias=1
FontColor=#FontColor#
FontSize=(11*#Scale#)
SolidColor=0,0,0,1

[RegularText]
FontFace=#Font#
AntiAlias=1
FontColor=#FontColor#
FontSize=(11*#Scale#)
SolidColor=0,0,0,1
