[Variables]
ReplaceWin=1
Mode=1
CustomFormat=0
CustomTimeFormat=%c
ShowSec=0

StartText=Welcome back!
IconName=Core

FixW=590
MinH=0

Font=Segoe UI
Scale=1
Corner=1
Stroke=0
Edge=15

Position=CC
ScreenPadding=10

Animated=2
EaseType=OutSine
AniDir=Bottom
AniSteps=10

TypeToSearch=0
Blur=None
BlurCorner=RoundSmall

Module1=Weather
Module2=Volume
Module3=Resource
Module4=None
Module5=None

Accent=242, 52, 0
Alpha=255
Color=12,12,12
Border=28,28,28
FontColor=242,240,255
DarkColor=120,120,120
BoxBorder=35,35,35
BoxColor=35,35,35
FetchImage=0

BackgroundMod=0

;;╔══════════════════════════════════════════════════════════════════════════════════════════════════════╗
;;║ METERSTYLES                                                                                          ║
;;╚══════════════════════════════════════════════════════════════════════════════════════════════════════╝


[BoldText]
FontFace=#Font#
FontWeight=800
AntiAlias=1
FontColor=#FontColor#
FontSize=(11*#Scale#)
SolidColor=0,0,0,1

[SemiBoldText]
FontFace=#Font#
FontWeight=500
AntiAlias=1
FontColor=#FontColor#
FontSize=(11*#Scale#)
SolidColor=0,0,0,1

[RegularText]
FontFace=#Font#
AntiAlias=1
FontColor=#FontColor#
FontSize=(11*#Scale#)
SolidColor=0,0,0,1
